AZURE_OPENAI_KEY = "4zrKHNuVJMF2SpxjYd6x1zU5WET9qNrl6SCZWg26itjWcCVx3b7mJQQJ99BFACfhMk5XJ3w3AAAAACOGUoY1"
AZURE_OPENAI_ENDPOINT = "https://kaila-mbr7yuo6-swedencentral.cognitiveservices.azure.com/"
AZURE_OPENAI_DEPLOYMENT = "gpt-4.1"
GOOGLE_CLIENT_ID = "1068458202234-uj612goi35m87qupgpmmj7408n0t029f.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
REDIRECT_URI = "http://localhost:8501"